<?php
// #ddev-generated
/**
 * Main SimpleSAMLphp configuration bootstrap.
 * This loads the baseline configuration from the package distribution and applies DDEV overrides.
 *
 * DO NOT EDIT THIS FILE.
 * If you need to customize settings, use config-override.php.
 */

// Load baseline config.php.dist from unshadowed defaults directory
$defaultConfigPath = '/var/www/simplesamlphp/defaults/config.php.dist';
if (file_exists($defaultConfigPath)) {
    include $defaultConfigPath;
} else {
    $config = [];
}

// Apply DDEV-specific environment overrides
$idp_host = getenv('SAML_IDP_PRIMARY_HOST');

$config['baseurlpath'] = 'https://' . $idp_host . '/simplesaml/';
$config['useCleanURLs'] = true;
$config['metadatadir'] = '/var/www/simplesamlphp/metadata';
$config['certdir'] = '/var/www/simplesamlphp/certs';
$config['tempdir'] = '/var/www/simplesamlphp/var/temp';
$config['cachedir'] = '/var/www/simplesamlphp/var/cache';

// Set admin password and secret salt with secure fallback/static defaults
$config['auth.adminpassword'] = getenv('SSP_ADMIN_PASSWORD') ?: 'admin';
$config['secretsalt'] = getenv('SSP_SECRET_SALT') ?: 'default_development_secret_salt_12345678_override_me';

// Explicitly enable SAML IdP and exampleauth module
$config['enable.saml20-idp'] = true;
if (!isset($config['module.enable']) || !is_array($config['module.enable'])) {
    $config['module.enable'] = [];
}
$config['module.enable']['exampleauth'] = true;

// Standard development defaults
$config['logging.handler'] = 'errorlog';
$config['logging.level'] = SimpleSAML\Logger::DEBUG;
$config['store.type'] = 'phpsession';

// Include user-defined config overrides if present
$overrideFile = __DIR__ . '/config-override.php';
if (file_exists($overrideFile)) {
    include $overrideFile;
}
